# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'design_IP_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'design_IP_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_pearson/Demo_IP_HLS_pearson.srcs/sources_1/bd/design_IP/ip/design_IP_rst_clk_wiz_0_100M_0/design_IP_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
