# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/simple_processor/simple_processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor || ORIG_REF_NAME==simple_processor} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_processing_system7_0_0/simple_processor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_processing_system7_0_0 || ORIG_REF_NAME==simple_processor_processing_system7_0_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_axi_gpio_0_0/simple_processor_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_axi_gpio_0_0 || ORIG_REF_NAME==simple_processor_axi_gpio_0_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_axi_gpio_1_1/simple_processor_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_axi_gpio_1_1 || ORIG_REF_NAME==simple_processor_axi_gpio_1_1} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_xbar_0/simple_processor_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_xbar_0 || ORIG_REF_NAME==simple_processor_xbar_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_ps7_0_axi_periph_0/simple_processor_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_ps7_0_axi_periph_0 || ORIG_REF_NAME==simple_processor_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_rst_ps7_0_100M_0/simple_processor_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_rst_ps7_0_100M_0 || ORIG_REF_NAME==simple_processor_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_fibonacci_0_0/simple_processor_fibonacci_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_fibonacci_0_0 || ORIG_REF_NAME==simple_processor_fibonacci_0_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_axi_gpio_2_0/simple_processor_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_axi_gpio_2_0 || ORIG_REF_NAME==simple_processor_axi_gpio_2_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_slice_app_module_0_0/simple_processor_slice_app_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_slice_app_module_0_0 || ORIG_REF_NAME==simple_processor_slice_app_module_0_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_xlconcat_0_0/simple_processor_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_xlconcat_0_0 || ORIG_REF_NAME==simple_processor_xlconcat_0_0} -quiet] -quiet

# IP: bd/simple_processor/ip/simple_processor_auto_pc_0/simple_processor_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simple_processor_auto_pc_0 || ORIG_REF_NAME==simple_processor_auto_pc_0} -quiet] -quiet

# XDC: bd/simple_processor/simple_processor_ooc.xdc
