# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_mul/Demo_IP_HLS_mul.srcs/sources_1/bd/design_IP/ip/design_IP_auto_pc_2/design_IP_auto_pc_2.xci
# IP: The module: 'design_IP_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_mul/Demo_IP_HLS_mul.srcs/sources_1/bd/design_IP/ip/design_IP_auto_pc_2/design_IP_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_mul/Demo_IP_HLS_mul.srcs/sources_1/bd/design_IP/ip/design_IP_auto_pc_2/design_IP_auto_pc_2.xci
# IP: The module: 'design_IP_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_mul/Demo_IP_HLS_mul.srcs/sources_1/bd/design_IP/ip/design_IP_auto_pc_2/design_IP_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
