# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/anis/A2/Hardware/HLS/Block_Matrix_HLS_32/block_matrix_32/solution1/impl/vhdl/multiply_block_32.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: bd/bd_0/bd_0_ooc.xdc
