#pragma line 1 "Sobel_Kernel_HLS/solution1/sobel.cpp" ::: -10
#pragma line 1 "Sobel_Kernel_HLS/solution1/sobel.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 145 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 407 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 188
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 191
#pragma line 6 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "Sobel_Kernel_HLS/solution1/sobel.cpp" 2 ::: 195
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 197
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 224
#pragma line 122 "/usr/include/features.h" 3 4 ::: 321
#pragma line 156 "/usr/include/features.h" 3 4 ::: 346
#pragma line 180 "/usr/include/features.h" 3 4 ::: 348
#pragma line 191 "/usr/include/features.h" 3 4 ::: 351
#pragma line 343 "/usr/include/features.h" 3 4 ::: 382
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 386
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 421
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 428
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 451
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 492
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 498
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 516
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 522
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 526
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 528
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 532
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 542
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 595
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 636
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 661
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 685
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 686
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 688
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 690
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 691
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 716
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 727
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 732
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 733
#pragma line 27 "/usr/include/math.h" 2 3 4 ::: 734
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 740
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 766
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 798
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 799
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 804
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 829
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 831
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 856
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 857
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 876
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 880
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 904
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 908
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 933
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 938
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 955
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 961
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 968
#pragma line 83 "/usr/include/math.h" 3 4 ::: 974
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 975
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1359
#pragma line 93 "/usr/include/math.h" 3 4 ::: 1360
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1363
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1364
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1748
#pragma line 139 "/usr/include/math.h" 3 4 ::: 1749
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1752
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1753
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 2137
#pragma line 167 "/usr/include/math.h" 3 4 ::: 2138
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2205
#pragma line 268 "/usr/include/math.h" 3 4 ::: 2207
#pragma line 282 "/usr/include/math.h" 3 4 ::: 2209
#pragma line 304 "/usr/include/math.h" 3 4 ::: 2219
#pragma line 318 "/usr/include/math.h" 3 4 ::: 2221
#pragma line 346 "/usr/include/math.h" 3 4 ::: 2237
#pragma line 411 "/usr/include/math.h" 3 4 ::: 2291
#pragma line 428 "/usr/include/math.h" 3 4 ::: 2293
#pragma line 448 "/usr/include/math.h" 3 4 ::: 2297
#pragma line 470 "/usr/include/math.h" 3 4 ::: 2312
#pragma line 534 "/usr/include/math.h" 3 4 ::: 2368
#pragma line 2 "Sobel_Kernel_HLS/solution1/sobel.cpp" 2 ::: 2370
#pragma line 2 "Sobel_Kernel_HLS/solution1/sobel.cpp" ::: 2372
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2374
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2407
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2443
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2446
#pragma line 92 "/usr/include/string.h" 3 4 ::: 2483
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2552
#pragma line 39 "/usr/include/xlocale.h" ::: 2594
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 2599
#pragma line 194 "/usr/include/string.h" 3 4 ::: 2625
#pragma line 207 "/usr/include/string.h" 3 4 ::: 2627
#pragma line 231 "/usr/include/string.h" 3 4 ::: 2629
#pragma line 258 "/usr/include/string.h" 3 4 ::: 2634
#pragma line 310 "/usr/include/string.h" 3 4 ::: 2664
#pragma line 337 "/usr/include/string.h" 3 4 ::: 2669
#pragma line 431 "/usr/include/string.h" 3 4 ::: 2751
#pragma line 484 "/usr/include/string.h" 3 4 ::: 2782
#pragma line 512 "/usr/include/string.h" 3 4 ::: 2788
#pragma line 658 "/usr/include/string.h" 3 4 ::: 2877
#pragma line 3 "Sobel_Kernel_HLS/solution1/sobel.cpp" 2 ::: 2879
