# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_empty/Demo_IP_HLS_empty.srcs/sources_1/bd/design_IP/ip/design_IP_multiply_block_0_0/design_IP_multiply_block_0_0.xci
# IP: The module: 'design_IP_multiply_block_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_empty/Demo_IP_HLS_empty.srcs/sources_1/bd/design_IP/ip/design_IP_multiply_block_0_0/constraints/multiply_block_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_multiply_block_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_empty/Demo_IP_HLS_empty.srcs/sources_1/bd/design_IP/ip/design_IP_multiply_block_0_0/design_IP_multiply_block_0_0.xci
# IP: The module: 'design_IP_multiply_block_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Vivado/Demo_IP_HLS/Demo_IP_HLS_empty/Demo_IP_HLS_empty.srcs/sources_1/bd/design_IP/ip/design_IP_multiply_block_0_0/constraints/multiply_block_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_multiply_block_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
