# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_algorithms_ARM/design_algorithms_ARM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_algorithms_ARM || ORIG_REF_NAME==design_algorithms_ARM} -quiet] -quiet

# IP: bd/design_algorithms_ARM/ip/design_algorithms_ARM_processing_system7_0_0/design_algorithms_ARM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_algorithms_ARM_processing_system7_0_0 || ORIG_REF_NAME==design_algorithms_ARM_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_algorithms_ARM/ip/design_algorithms_ARM_axi_timer_0_0/design_algorithms_ARM_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_algorithms_ARM_axi_timer_0_0 || ORIG_REF_NAME==design_algorithms_ARM_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_algorithms_ARM/ip/design_algorithms_ARM_ps7_0_axi_periph_0/design_algorithms_ARM_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_algorithms_ARM_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_algorithms_ARM_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_algorithms_ARM/ip/design_algorithms_ARM_rst_ps7_0_100M_0/design_algorithms_ARM_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_algorithms_ARM_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_algorithms_ARM_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_algorithms_ARM/ip/design_algorithms_ARM_auto_pc_0/design_algorithms_ARM_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_algorithms_ARM_auto_pc_0 || ORIG_REF_NAME==design_algorithms_ARM_auto_pc_0} -quiet] -quiet

# XDC: bd/design_algorithms_ARM/design_algorithms_ARM_ooc.xdc
