# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_multi/design_multi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi || ORIG_REF_NAME==design_multi} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_processing_system7_0_0/design_multi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_processing_system7_0_0 || ORIG_REF_NAME==design_multi_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_axi_gpio_0_0/design_multi_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_axi_gpio_0_0 || ORIG_REF_NAME==design_multi_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_ps7_0_axi_periph_0/design_multi_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_multi_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_rst_ps7_0_100M_0/design_multi_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_multi_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_microblaze_0_0/design_multi_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_microblaze_0_0 || ORIG_REF_NAME==design_multi_microblaze_0_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_dlmb_v10_0/design_multi_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_dlmb_v10_0 || ORIG_REF_NAME==design_multi_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_ilmb_v10_0/design_multi_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_ilmb_v10_0 || ORIG_REF_NAME==design_multi_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_dlmb_bram_if_cntlr_0/design_multi_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_multi_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_ilmb_bram_if_cntlr_0/design_multi_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_multi_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_lmb_bram_0/design_multi_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_lmb_bram_0 || ORIG_REF_NAME==design_multi_lmb_bram_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_microblaze_0_axi_periph_0/design_multi_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_multi_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_microblaze_0_axi_intc_0/design_multi_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_multi_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_microblaze_0_xlconcat_0/design_multi_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_multi_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_mdm_1_0/design_multi_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_mdm_1_0 || ORIG_REF_NAME==design_multi_mdm_1_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_clk_wiz_1_0/design_multi_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_clk_wiz_1_0 || ORIG_REF_NAME==design_multi_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_rst_clk_wiz_1_100M_0/design_multi_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_multi_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_axi_smc_0/design_multi_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_axi_smc_0 || ORIG_REF_NAME==design_multi_axi_smc_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_xbar_0/design_multi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_xbar_0 || ORIG_REF_NAME==design_multi_xbar_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_xbar_1/design_multi_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_xbar_1 || ORIG_REF_NAME==design_multi_xbar_1} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_axi_bram_ctrl_0_bram_0_0/design_multi_axi_bram_ctrl_0_bram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_axi_bram_ctrl_0_bram_0_0 || ORIG_REF_NAME==design_multi_axi_bram_ctrl_0_bram_0_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_axi_bram_ctrl_0_1/design_multi_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_multi_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_smartconnect_0_0/design_multi_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_smartconnect_0_0 || ORIG_REF_NAME==design_multi_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_axi_bram_ctrl_1_0/design_multi_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_multi_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_axi_bram_ctrl_1_bram_0/design_multi_axi_bram_ctrl_1_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==design_multi_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_Kmeans_0_0/design_multi_Kmeans_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_Kmeans_0_0 || ORIG_REF_NAME==design_multi_Kmeans_0_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_smartconnect_1_0/design_multi_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_smartconnect_1_0 || ORIG_REF_NAME==design_multi_smartconnect_1_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_xbar_3/design_multi_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_xbar_3 || ORIG_REF_NAME==design_multi_xbar_3} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_axi_interconnect_0_0/design_multi_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_axi_interconnect_0_0 || ORIG_REF_NAME==design_multi_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_auto_pc_1/design_multi_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_auto_pc_1 || ORIG_REF_NAME==design_multi_auto_pc_1} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_auto_pc_0/design_multi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_auto_pc_0 || ORIG_REF_NAME==design_multi_auto_pc_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_auto_pc_2/design_multi_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_auto_pc_2 || ORIG_REF_NAME==design_multi_auto_pc_2} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_s00_mmu_0/design_multi_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_s00_mmu_0 || ORIG_REF_NAME==design_multi_s00_mmu_0} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_auto_pc_4/design_multi_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_auto_pc_4 || ORIG_REF_NAME==design_multi_auto_pc_4} -quiet] -quiet

# IP: bd/design_multi/ip/design_multi_auto_pc_3/design_multi_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multi_auto_pc_3 || ORIG_REF_NAME==design_multi_auto_pc_3} -quiet] -quiet

# XDC: bd/design_multi/design_multi_ooc.xdc
