# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/A2_project/Board_Project_A2_multi_processor.srcs/sources_1/bd/design_multi/ip/design_multi_auto_pc_3/design_multi_auto_pc_3.xci
# IP: The module: 'design_multi_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Board_Project_A2_multi_processor.srcs/sources_1/bd/design_multi/ip/design_multi_auto_pc_3/design_multi_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_multi_auto_pc_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/A2_project/Board_Project_A2_multi_processor.srcs/sources_1/bd/design_multi/ip/design_multi_auto_pc_3/design_multi_auto_pc_3.xci
# IP: The module: 'design_multi_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/A2_project/Board_Project_A2_multi_processor.srcs/sources_1/bd/design_multi/ip/design_multi_auto_pc_3/design_multi_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_multi_auto_pc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
