# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_mb/design_mb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb || ORIG_REF_NAME==design_mb} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_processing_system7_0_0/design_mb_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_processing_system7_0_0 || ORIG_REF_NAME==design_mb_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_clk_wiz_0_0/design_mb_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_clk_wiz_0_0 || ORIG_REF_NAME==design_mb_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_0/design_mb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_0 || ORIG_REF_NAME==design_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_dlmb_v10_7/design_mb_dlmb_v10_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_dlmb_v10_7 || ORIG_REF_NAME==design_mb_dlmb_v10_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_ilmb_v10_7/design_mb_ilmb_v10_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_ilmb_v10_7 || ORIG_REF_NAME==design_mb_ilmb_v10_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_dlmb_bram_if_cntlr_7/design_mb_dlmb_bram_if_cntlr_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_dlmb_bram_if_cntlr_7 || ORIG_REF_NAME==design_mb_dlmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_ilmb_bram_if_cntlr_7/design_mb_ilmb_bram_if_cntlr_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_ilmb_bram_if_cntlr_7 || ORIG_REF_NAME==design_mb_ilmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_lmb_bram_7/design_mb_lmb_bram_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_lmb_bram_7 || ORIG_REF_NAME==design_mb_lmb_bram_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_axi_intc_5/design_mb_microblaze_0_axi_intc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_axi_intc_5 || ORIG_REF_NAME==design_mb_microblaze_0_axi_intc_5} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_xlconcat_5/design_mb_microblaze_0_xlconcat_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_xlconcat_5 || ORIG_REF_NAME==design_mb_microblaze_0_xlconcat_5} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_mdm_1_7/design_mb_mdm_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_mdm_1_7 || ORIG_REF_NAME==design_mb_mdm_1_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_rst_clk_wiz_0_100M_7/design_mb_rst_clk_wiz_0_100M_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_rst_clk_wiz_0_100M_7 || ORIG_REF_NAME==design_mb_rst_clk_wiz_0_100M_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_xbar_5/design_mb_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_xbar_5 || ORIG_REF_NAME==design_mb_xbar_5} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_ps7_0_axi_periph_1/design_mb_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_mb_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_rst_clk_wiz_0_100M_1_2/design_mb_rst_clk_wiz_0_100M_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_rst_clk_wiz_0_100M_1_2 || ORIG_REF_NAME==design_mb_rst_clk_wiz_0_100M_1_2} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_xbar_6/design_mb_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_xbar_6 || ORIG_REF_NAME==design_mb_xbar_6} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_mem_intercon_0/design_mb_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_mem_intercon_0 || ORIG_REF_NAME==design_mb_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_xbar_7/design_mb_xbar_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_xbar_7 || ORIG_REF_NAME==design_mb_xbar_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_interconnect_0_0/design_mb_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_interconnect_0_0 || ORIG_REF_NAME==design_mb_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_timer_0_0/design_mb_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_timer_0_0 || ORIG_REF_NAME==design_mb_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_bram_ctrl_0_0/design_mb_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_mb_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_bram_ctrl_0_bram_0/design_mb_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_mb_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_xbar_8/design_mb_xbar_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_xbar_8 || ORIG_REF_NAME==design_mb_xbar_8} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_interconnect_1_0/design_mb_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_interconnect_1_0 || ORIG_REF_NAME==design_mb_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_2/design_mb_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_2 || ORIG_REF_NAME==design_mb_auto_pc_2} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_3/design_mb_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_3 || ORIG_REF_NAME==design_mb_auto_pc_3} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_0/design_mb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_0 || ORIG_REF_NAME==design_mb_auto_pc_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_1/design_mb_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_1 || ORIG_REF_NAME==design_mb_auto_pc_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_us_0/design_mb_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_us_0 || ORIG_REF_NAME==design_mb_auto_us_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_cc_0/design_mb_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_cc_0 || ORIG_REF_NAME==design_mb_auto_cc_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_4/design_mb_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_4 || ORIG_REF_NAME==design_mb_auto_pc_4} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_ds_0/design_mb_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_ds_0 || ORIG_REF_NAME==design_mb_auto_ds_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_5/design_mb_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_5 || ORIG_REF_NAME==design_mb_auto_pc_5} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_ds_1/design_mb_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_ds_1 || ORIG_REF_NAME==design_mb_auto_ds_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_6/design_mb_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_6 || ORIG_REF_NAME==design_mb_auto_pc_6} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_7/design_mb_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_7 || ORIG_REF_NAME==design_mb_auto_pc_7} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_cc_1/design_mb_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_cc_1 || ORIG_REF_NAME==design_mb_auto_cc_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_8/design_mb_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_8 || ORIG_REF_NAME==design_mb_auto_pc_8} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_cc_2/design_mb_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_cc_2 || ORIG_REF_NAME==design_mb_auto_cc_2} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_9/design_mb_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_9 || ORIG_REF_NAME==design_mb_auto_pc_9} -quiet] -quiet

# XDC: bd/design_mb/design_mb_ooc.xdc
