# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Qlala/Documents/M2_SETI/A2/git/A2/Hardware/Vivado/multiCPU/prj_BRAM/prj_BRAM.srcs/sources_1/bd/design_mb/ip/design_mb_xbar_6/design_mb_xbar_6.xci
# IP: The module: 'design_mb_xbar_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Qlala/Documents/M2_SETI/A2/git/A2/Hardware/Vivado/multiCPU/prj_BRAM/prj_BRAM.srcs/sources_1/bd/design_mb/ip/design_mb_xbar_6/design_mb_xbar_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_xbar_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Qlala/Documents/M2_SETI/A2/git/A2/Hardware/Vivado/multiCPU/prj_BRAM/prj_BRAM.srcs/sources_1/bd/design_mb/ip/design_mb_xbar_6/design_mb_xbar_6.xci
# IP: The module: 'design_mb_xbar_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Qlala/Documents/M2_SETI/A2/git/A2/Hardware/Vivado/multiCPU/prj_BRAM/prj_BRAM.srcs/sources_1/bd/design_mb/ip/design_mb_xbar_6/design_mb_xbar_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_xbar_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
